// export const CHANGE_BREADCRUMB = "CHANGE_BREADCRUMB";
// export const SELECT_MEDICATION = "SELECT_MEDICATION";
// export const SIGN_MEDICATION = "SIGN_MEDICATION";
// export const ACTIVE_MEDICATION = "ACTIVE_MEDICATION";
// export const SELECT_ORDER = "SELECT_ORDER";
// export const SIGN_ORDER = "SIGN_ORDER";
// export const CHANGE_DIAGNOSIS = "CHANGE_DIAGNOSIS";
// export const SAVE_COMPLAINTS = "SAVE_COMPLAINTS";
// export const SAVE_CLINIC_HISTORY = "SAVE_CLINIC_HISTORY";
// export const SAVE_MEDICATION = "SAVE_MEDICATION";
// export const SAVE_ADMISSION_DETAIL = "SAVE_ADMISSION_DETAIL";
// export const SAVE_SYSTEMIC_REVIEW = "SAVE_SYSTEMIC_REVIEW";
// export const SAVE_REFERRALS = "SAVE_REFERRALS";
// export const SAVE_CARETEAM = "SAVE_CARETEAM";
// export const CHANGE_VITAL = "CHANGE_VITAL";
// export const CHANGE_VITAL_CONFIG = "CHANGE_VITAL_CONFIG";
// export const SAVE_EHR_ID = "SAVE_EHR_ID";
// export const SAVE_GENERAL_EXAMINATION_DATA = "SAVE_GENERAL_EXAMINATION_DATA";
// export const CHANGE_NOTIFICATION_DATA = "CHANGE_NOTIFICATION_DATA";
// export const SAVE_EXAMINATION_DATA = "SAVE_EXAMINATION_DATA";
// export const IS_CHANGES = "IS_CHANGES";
// export const SOAP_INITIATOR = "SOAP_INITIATOR";
// export const ADD_REFERRALS = "ADD_REFERRALS";
// export const DELETE_REFERRALS = "DELETE_REFERRALS";
// export const SAVE_ALLERGIES = "SAVE_ALLERGIES";
// export const SAVE_DOCTOR_NOTES = "SAVE_DOCTOR_NOTES";
// export const SAVE_CLICKED_APPOINTMENT = "SAVE_CLICKED_APPOINTMENT";
// export const SAVE_APPOINTMENT_DATA = "SAVE_APPOINTMENT_DATA";
// export const SAVEISADMISSIONREQUEST = "SAVEISADMISSIONREQUEST";
// export const SAVE_IS_CHANGES_IN_ADT = "SAVE_IS_CHANGES_IN_ADT";

// export const PATIENT_COMPOSITE_REQUEST = "PATIENT_COMPOSITE_REQUEST";
// export const PATIENT_COMPOSITE_SUCCESS = "PATIENT_COMPOSITE_SUCCESS";

// export const GET_PATIENT_DETAILS_BY_ID_REQUEST = "GET_PATIENT_DETAILS_BY_ID_REQUEST";
// export const GET_PATIENT_DETAILS_BY_ID_SUCCESS = "GET_PATIENT_DETAILS_BY_ID_SUCCESS";
// export const GET_PATIENT_DETAILS_BY_ID_FAIL = "GET_PATIENT_DETAILS_BY_ID_FAIL";

// export const GET_FREE_SLOTS_REQUEST = "GET_FREE_SLOTS_REQUEST";
// export const GET_FREE_SLOTS_REQUEST_SUCCESS = "GET_FREE_SLOTS_REQUEST_SUCCESS";
// export const GET_FREE_SLOTS_REQUEST_FAIL = "GET_FREE_SLOTS_REQUEST_FAIL";

// export const ADD_OR_REMOVE_ORDERS = "ADD_OR_REMOVE_ORDERS";
// export const RESET_NEW_ORDERS = "RESET_NEW_ORDERS";

// export const CREATE_NEW_ORDERS_REQUEST = "CREATE_NEW_ORDERS_REQUEST";
// export const CREATE_NEW_ORDERS_SUCCESS = "CREATE_NEW_ORDERS_SUCCESS";
// export const CREATE_NEW_ORDERS_FAIL = "CREATE_NEW_ORDERS_FAIL";


// export const HANDLE_NOTIFICATION = "HANDLE_NOTIFICATION";

// export const GET_PENDING_ORDERS_REQUEST = "GET_PENDING_ORDERS_REQUEST";
// export const GET_PENDING_ORDERS_SUCCESS = "GET_PENDING_ORDERS_SUCCESS";
// export const GET_PENDING_ORDERS_FAIL = "GET_PENDING_ORDERS_FAIL";

// export const GET_PENDING_ORDERS_BY_ID_REQUEST = "GET_PENDING_ORDERS_BY_ID_REQUEST";
// export const GET_PENDING_ORDERS_BY_ID_SUCCESS = "GET_PENDING_ORDERS_BY_ID_SUCCESS";
// export const GET_PENDING_ORDERS_BY_ID_FAIL = "GET_PENDING_ORDERS_BY_ID_FAIL";
// export const GET_PENDING_ORDERS_BY_ID_RESET = "GET_PENDING_ORDERS_BY_ID_RESET";

// export const GET_BOOKED_APPOINTMENT_REQUEST = "GET_BOOKED_APPOINTMENT_REQUEST";
// export const GET_BOOKED_APPOINTMENT_SUCCESS = "GET_BOOKED_APPOINTMENT_SUCCESS";
// export const GET_BOOKED_APPOINTMENT_FAIL = "GET_BOOKED_APPOINTMENT_FAIL";

// export const GET_ALL_BILLING_PATIENTS_REQUEST = "GET_ALL_BILLING_PATIENTS_REQUEST";
// export const GET_ALL_BILLING_PATIENTS_SUCCESS = "GET_ALL_BILLING_PATIENTS_SUCCESS";
// export const GET_ALL_BILLING_PATIENTS_FAIL = "GET_ALL_BILLING_PATIENTS_FAIL";

// export const GET_BILLABLE_PATIENTS_REQUEST = "GET_BILLABLE_PATIENTS_REQUEST";
// export const GET_BILLABLE_PATIENTS_SUCCESS = "GET_BILLABLE_PATIENTS_SUCCESS";
// export const GET_BILLABLE_PATIENTS_FAIL = "GET_BILLABLE_PATIENTS_FAIL";

// export const GET_PRINTED_INVOICE_REQUEST = "GET_PRINTED_INVOICE_REQUEST";
// export const GET_PRINTED_INVOICE_SUCCESS = "GET_PRINTED_INVOICE_SUCCESS";
// export const GET_PRINTED_INVOICE_FAIL = "GET_PRINTED_INVOICE_FAIL";

// export const GET_REFUND_PRINTED_INVOICE_REQUEST = "GET_REFUND_PRINTED_INVOICE_REQUEST";
// export const GET_REFUND_PRINTED_INVOICE_SUCCESS = "GET_REFUND_PRINTED_INVOICE_SUCCESS";
// export const GET_REFUND_PRINTED_INVOICE_FAIL = "GET_REFUND_PRINTED_INVOICE_FAIL";

// export const CREATE_INVOICE_DETAILS = "CREATE_INVOICE_DETAILS";
// export const RESET_INVOICE_DETAILS = "RESET_INVOICE_DETAILS"

// export const CREATE_NEW_INVOICE_REQUEST = "CREATE_NEW_INVOICE_REQUEST";
// export const CREATE_NEW_INVOICE_SUCCESS = "CREATE_NEW_INVOICE_SUCCESS";
// export const CREATE_NEW_INVOICE_FAIL = "CREATE_NEW_INVOICE_FAIL";

// export const HANDLE_MODAL = "HANDLE_MODAL";

// export const GET_SAVED_INVOICE_REQUEST = "GET_SAVED_INVOICE_REQUEST";
// export const GET_SAVED_INVOICE_SUCCESS = "GET_SAVED_INVOICE_SUCCESS";
// export const GET_SAVED_INVOICE_FAIL = "GET_SAVED_INVOICE_FAIL";

// export const GET_PATIENT_DETAILS_BANNER_REQUEST = "GET_PATIENT_DETAILS_BANNER_REQUEST";
// export const GET_PATIENT_DETAILS_BANNER_SUCCESS = "GET_PATIENT_DETAILS_BANNER_SUCCESS";
// export const GET_PATIENT_DETAILS_BANNER_FAIL = "GET_PATIENT_DETAILS_BANNER_FAIL";

// export const GET_BILLING_SUMMARY_REQUEST = "GET_BILLING_SUMMARY_REQUEST";
// export const GET_BILLING_SUMMARY_SUCCESS = "GET_BILLING_SUMMARY_SUCCESS";
// export const GET_BILLING_SUMMARY_FAIL = "GET_BILLING_SUMMARY_FAIL";

// export const GET_DASHBOARD_STATUS_RESET = "GET_DASHBOARD_STATUS_RESET";
// export const CHANGE_DASHBOARD_STATUS = "CHANGE_DASHBOARD_STATUS";

// export const GET_DEPARTMENT_STAFF_REGISTRATION = "GET_DEPARTMENT_STAFF_REGISTRATION";
// export const CREATE_DOCTOR_VISIT_PAYLOAD = "CREATE_DOCTOR_VISIT_PAYLOAD";
// export const RESET_DOCTOR_VISIT_PAYLOAD = "RESET_DOCTOR_VISIT_PAYLOAD";
// export const REMOVE_ELEMENT_FROM_DOCTOR_VISIT_PAYLOAD = "REMOVE_ELEMENT_FROM_DOCTOR_VISIT_PAYLOAD";
// export const UPDATE_DOCTOR_VISIT_PAYLOAD = "UPDATE_DOCTOR_VISIT_PAYLOAD";
// export const SELECTED_ELEMENT_DOCTOR_VISIT = "SELECTED_ELEMENT_DOCTOR_VISIT"

// export const SAVE_OPD_PREPARED_DRUGS = "SAVE_OPD_PREPARED_DRUGS"

// export const GET_SERVICE_MASTER_PRICE_BY_ID_REQUEST = "GET_SERVICE_MASTER_PRICE_BY_ID_REQUEST"
// export const GET_SERVICE_MASTER_PRICE_BY_ID_SUCCESS = "GET_SERVICE_MASTER_PRICE_BY_ID_SUCCESS"
// export const GET_SERVICE_MASTER_PRICE_BY_ID_FAIL = "GET_SERVICE_MASTER_PRICE_BY_ID_FAIL"

// export const GET_APPOINTMENT_DETAILS_BY_ID_REQUEST = "GET_APPOINTMENT_DETAILS_BY_ID_REQUEST"
// export const GET_APPOINTMENT_DETAILS_BY_ID_SUCCESS = "GET_APPOINTMENT_DETAILS_BY_ID_SUCCESS"
// export const GET_APPOINTMENT_DETAILS_BY_ID_FAIL = "GET_APPOINTMENT_DETAILS_BY_ID_FAIL"

// export const GET_USER_DETAILS_BY_ID_REQUEST = "GET_USER_DETAILS_BY_ID_REQUEST"
// export const GET_USER_DETAILS_BY_ID_SUCCESS = "GET_USER_DETAILS_BY_ID_SUCCESS"
// export const GET_USER_DETAILS_BY_ID_FAIL = "GET_USER_DETAILS_BY_ID_FAIL"

// export const SAVE_PHARMACY_BANNER = "SAVE_PHARMACY_BANNER"

// export const GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_REQUEST = "GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_REQUEST"
// export const GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_SUCCESS = "GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_SUCCESS"
// export const GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_FAIL = "GET_COMPOSITE_DATA_FOR_STAFF_REGISTRATION_FAIL"

// export const OPD_PRESCRIPTION = "OPD_PRESCRIPTION"
// export const OPD_PHARMACY_PREPARE = "OPD_PHARMACY_PREPARE"
// export const OPD_PHARMACY_VALIDATE = "OPD_PHARMACY_VALIDATE"
// export const OPD_PHARMACY_DELIVER = "OPD_PHARMACY_DELIVER"
// export const PRESCRIPTION_SLIP = "PRESCRIPTION_SLIP"

// export const OTC_PRESCRIPTION_ID = "OTC_PRESCRIPTION_ID"
// export const OTC_PRESCRIPTION = "OTC_PRESCRIPTION"
// export const OTC_PHARMACY_PREPARE = "OTC_PHARMACY_PREPARE"
// export const OTC_PHARMACY_VALIDATE = "OTC_PHARMACY_VALIDATE"
// export const OTC_PHARMACY_DELIVER = "OTC_PHARMACY_DELIVER"
// export const OTC_PRESCRIPTION_SLIP = "OTC_PRESCRIPTION_SLIP"
// export const OTC_PHARMACY_ITEM_PREPARE_SAVE = "OTC_PHARMACY_ITEM_PREPARE_SAVE"

// export const GET_PRESCRIPTION_DETAILS_FOR_BILLING_REQUEST = "GET_PRESCRIPTION_DETAILS_FOR_BILLING_REQUEST";
// export const GET_PRESCRIPTION_DETAILS_FOR_BILLING_SUCCESS = "GET_PRESCRIPTION_DETAILS_FOR_BILLING_SUCCESS";
// export const GET_PRESCRIPTION_DETAILS_FOR_BILLING_FAIL = "GET_PRESCRIPTION_DETAILS_FOR_BILLING_FAIL";

// export const GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_REQUEST = "GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_REQUEST";
// export const GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_SUCCESS = "GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_SUCCESS";
// export const GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_FAIL = "GET_PRESCRIPTION_DETAILS_BY_ID_FOR_BILLING_FAIL";

// export const GET_HOSPITAL_AND_DEPARTMENT_DETAILS_REQUEST = "GET_HOSPITAL_AND_DEPARTMENT_DETAILS_REQUEST";
// export const GET_HOSPITAL_AND_DEPARTMENT_DETAILS_SUCCESS = "GET_HOSPITAL_AND_DEPARTMENT_DETAILS_SUCCESS";
// export const GET_HOSPITAL_AND_DEPARTMENT_DETAILS_FAIL = "GET_HOSPITAL_AND_DEPARTMENT_DETAILS_FAIL";

// export const GET_GENERAL_ITEM_MASTER_DETAILS_REQUEST = "GET_GENERAL_ITEM_MASTER_DETAILS_REQUEST";
// export const GET_GENERAL_ITEM_MASTER_DETAILS_SUCCESS = "GET_GENERAL_ITEM_MASTER_DETAILS_SUCCESS";
// export const GET_GENERAL_ITEM_MASTER_DETAILS_FAIL = "GET_GENERAL_ITEM_MASTER_DETAILS_FAIL";

// export const CREATE_GENERAL_ITEM_MASTER_DETAILS_REQUEST = "CREATE_GENERAL_ITEM_MASTER_DETAILS_REQUEST";
// export const CREATE_GENERAL_ITEM_MASTER_DETAILS_SUCCESS = "CREATE_GENERAL_ITEM_MASTER_DETAILS_SUCCESS";
// export const CREATE_GENERAL_ITEM_MASTER_DETAILS_FAIL = "CREATE_GENERAL_ITEM_MASTER_DETAILS_FAIL";

// export const UPDATE_GENERAL_ITEM_MASTER_DETAILS_REQUEST = "UPDATE_GENERAL_ITEM_MASTER_DETAILS_REQUEST";
// export const UPDATE_GENERAL_ITEM_MASTER_DETAILS_SUCCESS = "UPDATE_GENERAL_ITEM_MASTER_DETAILS_SUCCESS";
// export const UPDATE_GENERAL_ITEM_MASTER_DETAILS_FAIL = "UPDATE_GENERAL_ITEM_MASTER_DETAILS_FAIL";

// export const UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_REQUEST = "UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_REQUEST";
// export const UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_SUCCESS = "UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_SUCCESS";
// export const UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_FAIL = "UPDATE_STATUS_GENERAL_ITEM_MASTER_DETAILS_FAIL";

// export const GET_ITEM_MASTER_COMPOSITE_REQUEST = "GET_ITEM_MASTER_COMPOSITE_REQUEST";
// export const GET_ITEM_MASTER_COMPOSITE_SUCCESS = "GET_ITEM_MASTER_COMPOSITE_SUCCESS";
// export const GET_ITEM_MASTER_COMPOSITE_FAIL = "GET_ITEM_MASTER_COMPOSITE_FAIL";

// export const HANDLE_TEST_DIRECTORY_MODAL = "HANDLE_TEST_DIRECTORY_MODAL";

// export const GET_ELEMENT_TEST_DIRECTORY_PRIVILEGES_TREE = "GET_ELEMENT_TEST_DIRECTORY_PRIVILEGES_TREE";
// export const CREATE_PRIVILEGES_TREE_PAYLOAD = "CREATE_PRIVILEGES_TREE_PAYLOAD";
// export const REMOVE_ELEMENT_FROM_PRIVILEGES_TREE = "REMOVE_ELEMENT_FROM_PRIVILEGES_TREE";
// export const RESET_PRIVILEGES_TREE_PAYLOAD = "RESET_PRIVILEGES_TREE_PAYLOAD";


// export const GET_ELEMENT_TEST_DIRECTORY_PRIORITY_TREE = "GET_ELEMENT_TEST_DIRECTORY_PRIORITY_TREE";
// export const CREATE_PRIORITY_TREE_PAYLOAD = "CREATE_PRIORITY_TREE_PAYLOAD";
// export const REMOVE_ELEMENT_FROM_PRIORITY_TREE = "REMOVE_ELEMENT_FROM_PRIORITY_TREE";
// export const RESET_PRIORITY_TREE_PAYLOAD = "RESET_PRIORITY_TREE_PAYLOAD";
// export const INCLUDE_ALL_IN_ELEMENT_FROM_PRIORITY_TREE = "INCLUDE_ALL_IN_ELEMENT_FROM_PRIORITY_TREE";
// export const INCLUDE_ALL_IN_ELEMENT_FROM_PRIVILEGE_TREE = "INCLUDE_ALL_IN_ELEMENT_FROM_PRIVILEGE_TREE";

// export const CREATE_LABORATORY_BASIC_DETAILS_REQUEST = "CREATE_LABORATORY_BASIC_DETAILS_REQUEST";
// export const CREATE_LABORATORY_BASIC_DETAILS_SUCCESS = "CREATE_LABORATORY_BASIC_DETAILS_SUCCESS";
// export const CREATE_LABORATORY_BASIC_DETAILS_FAIL = "CREATE_LABORATORY_BASIC_DETAILS_FAIL";

// export const CREATE_LABORATORY_CLASSIFICATION_DETAILS_REQUEST = "CREATE_LABORATORY_CLASSIFICATION_DETAILS_REQUEST";
// export const CREATE_LABORATORY_CLASSIFICATION_DETAILS_SUCCESS = "CREATE_LABORATORY_CLASSIFICATION_DETAILS_SUCCESS";
// export const CREATE_LABORATORY_CLASSIFICATION_DETAILS_FAIL = "CREATE_LABORATORY_CLASSIFICATION_DETAILS_FAIL";

// export const CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_REQUEST = "CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_REQUEST";
// export const CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_SUCCESS = "CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_SUCCESS";
// export const CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_FAIL = "CREATE_LABORATORY_RESULTS_AND_REPORTING_DETAILS_FAIL";

// export const GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_REQUEST = "GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_REQUEST"
// export const GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_SUCCESS = "GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_SUCCESS"
// export const GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_FAIL = "GET_COMPOSITE_DATA_FOR_TEST_DIRECTORY_FAIL"

// export const GET_LABORATORY_TEST_REQUEST = "GET_LABORATORY_TEST_REQUEST"
// export const GET_LABORATORY_TEST_SUCCESS = "GET_LABORATORY_TEST_SUCCESS"
// export const GET_LABORATORY_TEST_FAIL = "GET_LABORATORY_TEST_FAIL"

// export const GET_LABORATORY_TEST_STATISTICS_DATA_REQUEST = "GET_LABORATORY_TEST_STATISTICS_DATA_REQUEST"
// export const GET_LABORATORY_TEST_STATISTICS_DATA_SUCCESS = "GET_LABORATORY_TEST_STATISTICS_DATA_SUCCESS"
// export const GET_LABORATORY_TEST_STATISTICS_DATA_FAIL = "GET_LABORATORY_TEST_STATISTICS_DATA_FAIL"

// export const GET_LABORATORY_BOM_MASTERS_REQUEST = "GET_LABORATORY_BOM_MASTERS_REQUEST"
// export const GET_LABORATORY_BOM_MASTERS_SUCCESS = "GET_LABORATORY_BOM_MASTERS_SUCCESS"
// export const GET_LABORATORY_BOM_MASTERS_FAIL = "GET_LABORATORY_BOM_MASTERS_FAIL"

// export const GET_LABORATORY_BOM_OPTIONS_REQUEST = "GET_LABORATORY_BOM_OPTIONS_REQUEST"
// export const GET_LABORATORY_BOM_OPTIONS_SUCCESS = "GET_LABORATORY_BOM_OPTIONS_SUCCESS"
// export const GET_LABORATORY_BOM_OPTIONS_FAIL = "GET_LABORATORY_BOM_OPTIONS_FAIL"

// export const CREATE_LABORATORY_BOM_DETAILS_REQUEST = "CREATE_LABORATORY_BOM_DETAILS_REQUEST"
// export const CREATE_LABORATORY_BOM_DETAILS_SUCCESS = "CREATE_LABORATORY_BOM_DETAILS_SUCCESS"
// export const CREATE_LABORATORY_BOM_DETAILS_FAIL = "CREATE_LABORATORY_BOM_DETAILS_FAIL"

// export const DELETE_LABORATORY_BOM_DETAILS_REQUEST = "DELETE_LABORATORY_BOM_DETAILS_REQUEST"
// export const DELETE_LABORATORY_BOM_DETAILS_SUCCESS = "DELETE_LABORATORY_BOM_DETAILS_SUCCESS"
// export const DELETE_LABORATORY_BOM_DETAILS_FAIL = "DELETE_LABORATORY_BOM_DETAILS_FAIL"

// export const GET_LABORATORY_BOM_DETAILS_REQUEST = "GET_LABORATORY_BOM_DETAILS_REQUEST"
// export const GET_LABORATORY_BOM_DETAILS_SUCCESS = "GET_LABORATORY_BOM_DETAILS_SUCCESS"
// export const GET_LABORATORY_BOM_DETAILS_FAIL = "GET_LABORATORY_BOM_DETAILS_FAIL"

// export const GET_LABORATORY_LOINC_CODE_DATA_REQUEST = "GET_LABORATORY_LOINC_CODE_DATA_REQUEST";
// export const GET_LABORATORY_LOINC_CODE_DATA_SUCCESS = "GET_LABORATORY_LOINC_CODE_DATA_SUCCESS";
// export const GET_LABORATORY_LOINC_CODE_DATA_FAIL = "GET_LABORATORY_LOINC_CODE_DATA_FAIL";
// export const RESET_LABORATORY_LOINC_CODE_DATA = "RESET_LABORATORY_LOINC_CODE_DATA";

// export const GET_LABORATORY_CPT_CODE_DATA_REQUEST = "GET_LABORATORY_CPT_CODE_DATA_REQUEST";
// export const GET_LABORATORY_CPT_CODE_DATA_SUCCESS = "GET_LABORATORY_CPT_CODE_DATA_SUCCESS";
// export const GET_LABORATORY_CPT_CODE_DATA_FAIL = "GET_LABORATORY_CPT_CODE_DATA_FAIL";
// export const RESET_LABORATORY_CPT_CODE_DATA = "RESET_LABORATORY_CPT_CODE_DATA";

// export const GET_REFUND_REQUEST_LIST_REQUEST = "GET_REFUND_REQUEST_LIST_REQUEST"
// export const GET_REFUND_REQUEST_LIST_SUCCESS = "GET_REFUND_REQUEST_LIST_SUCCESS"
// export const GET_REFUND_REQUEST_LIST_ERROR = "GET_REFUND_REQUEST_LIST_ERROR"

// export const GET_REFUND_PATIENT_LIST_REQUEST = "GET_REFUND_PATIENT_LIST_REQUEST"
// export const GET_REFUND_PATIENT_LIST_SUCCESS = "GET_REFUND_PATIENT_LIST_SUCCESS"
// export const GET_REFUND_PATIENT_LIST_ERROR = "GET_REFUND_PATIENT_LIST_ERROR"

// export const GET_BILLING_STATISTICS_DATA_REQUEST = "GET_BILLING_STATISTICS_DATA_REQUEST"
// export const GET_BILLING_STATISTICS_DATA_SUCCESS = "GET_BILLING_STATISTICS_DATA_SUCCESS"
// export const GET_BILLING_STATISTICS_DATA_ERROR = "GET_BILLING_STATISTICS_DATA_ERROR"

// export const GET_REFUND_DETAILS_BY_ID_REQUEST = "GET_REFUND_DETAILS_BY_ID_REQUEST"
// export const GET_REFUND_DETAILS_BY_ID_SUCCESS = "GET_REFUND_DETAILS_BY_ID_SUCCESS"
// export const GET_REFUND_DETAILS_BY_ID_ERROR = "GET_REFUND_DETAILS_BY_ID_ERROR"

// export const GET_LOCATION_SUMMARY_DATA_REQUEST = "GET_LOCATION_SUMMARY_DATA_REQUEST"
// export const GET_LOCATION_SUMMARY_DATA_SUCCESS = "GET_LOCATION_SUMMARY_DATA_SUCCESS"
// export const GET_LOCATION_SUMMARY_DATA_ERROR = "GET_LOCATION_SUMMARY_DATA_ERROR"

// export const SET_REFUND_DETAILS_STORE = "SET_REFUND_DETAILS_STORE"
// export const RESET_REFUND_DETAILS_STORE = "RESET_REFUND_DETAILS_STORE"

// export const REFUND_AUTHORIZATION_REQUEST = "REFUND_AUTHORIZATION_REQUEST"
// export const REFUND_AUTHORIZATION_SUCCESS = "REFUND_AUTHORIZATION_SUCCESS"
// export const REFUND_AUTHORIZATION_ERROR = "REFUND_AUTHORIZATION_ERROR"

// export const ACCEPT_REFUND_AMOUNT_REQUEST = "ACCEPT_REFUND_AMOUNT_REQUEST"
// export const ACCEPT_REFUND_AMOUNT_SUCCESS = "ACCEPT_REFUND_AMOUNT_SUCCESS"
// export const ACCEPT_REFUND_AMOUNT_ERROR = "ACCEPT_REFUND_AMOUNT_ERROR"

// export const GET_TARIFF_DATA_REQUEST = "GET_TARIFF_DATA_REQUEST"
// export const GET_TARIFF_DATA_REQUEST_SUCCESS = "GET_TARIFF_DATA_REQUEST_SUCCESS"
// export const GET_TARIFF_DATA_REQUEST_ERROR = "GET_TARIFF_DATA_REQUEST_ERROR"

// export const GET_TARIFF_ROOM_CATEGORIES_REQUEST = "GET_TARIFF_ROOM_CATEGORIES_REQUEST"
// export const GET_TARIFF_ROOM_CATEGORIES_REQUEST_SUCCESS = "GET_TARIFF_ROOM_CATEGORIES_REQUEST_SUCCESS"
// export const GET_TARIFF_ROOM_CATEGORIES_REQUEST_ERROR = "GET_TARIFF_ROOM_CATEGORIES_REQUEST_ERROR"

// export const GET_AVAILABLE_SERVICES_REQUEST = "GET_AVAILABLE_SERVICES_REQUEST"
// export const GET_AVAILABLE_SERVICES_REQUEST_SUCCESS = "GET_AVAILABLE_SERVICES_REQUEST_SUCCESS"
// export const GET_AVAILABLE_SERVICES_REQUEST_ERROR = "GET_AVAILABLE_SERVICES_REQUEST_ERROR"

// export const GET_TARIFF_DETAIL_REQUEST = "GET_TARIFF_DETAIL_REQUEST"
// export const GET_TARIFF_DETAIL_REQUEST_SUCCESS = "GET_TARIFF_DETAIL_REQUEST_SUCCESS"
// export const GET_TARIFF_DETAIL_REQUEST_ERROR = "GET_TARIFF_DETAIL_REQUEST_ERROR"

// export const CREATE_NEW_TARIFF_REQUEST = "CREATE_NEW_TARIFF_REQUEST"
// export const CREATE_NEW_TARIFF_REQUEST_SUCCESS =  "CREATE_NEW_TARIFF_REQUEST_SUCCESS"
// export const CREATE_NEW_TARIFF_REQUEST_ERROR =  "CREATE_NEW_TARIFF_REQUEST_ERROR"

// export const UPDATE_ROOM_TARIFF_REQUEST = "UPDATE_ROOM_TARIFF_REQUEST"
// export const UPDATE_ROOM_TARIFF_REQUEST_SUCCESS = "UPDATE_ROOM_TARIFF_REQUEST_SUCCESS"
// export const UPDATE_ROOM_TARIFF_REQUEST_ERROR = "UPDATE_ROOM_TARIFF_REQUEST_ERROR"

// export const GET_TARIFF_CATEGORY_DETAIL_REQUEST = "GET_TARIFF_CATEGORY_DETAIL_REQUEST"
// export const GET_TARIFF_CATEGORY_DETAIL_REQUEST_SUCCESS = "GET_TARIFF_CATEGORY_DETAIL_REQUEST_SUCCESS"
// export const GET_TARIFF_CATEGORY_DETAIL_REQUEST_ERROR = "GET_TARIFF_CATEGORY_DETAIL_REQUEST_ERROR"

// export const GET_INWARD_TARIFF_UNITS_DATA_REQUEST = "GET_INWARD_TARIFF_UNITS_DATA_REQUEST"
// export const GET_INWARD_TARIFF_UNITS_DATA_REQUEST_SUCCESS = "GET_INWARD_TARIFF_UNITS_DATA_REQUEST_SUCCESS"
// export const GET_INWARD_TARIFF_UNITS_DATA_REQUEST_ERROR = "GET_INWARD_TARIFF_UNITS_DATA_REQUEST_ERROR"

// export const GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST = "GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST"
// export const GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST_SUCCESS = "GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST_SUCCESS"
// export const GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST_ERROR = "GET_TARIFF_OTHER_AVAILABLE_SERVICES_REQUEST_ERROR"

// export const GET_NEW_AVAILABLE_SERVICES_REQUEST = "GET_NEW_AVAILABLE_SERVICES_REQUEST"
// export const GET_NEW_AVAILABLE_SERVICES_REQUEST_SUCCESS = "GET_NEW_AVAILABLE_SERVICES_REQUEST_SUCCESS"
// export const GET_NEW_AVAILABLE_SERVICES_REQUEST_ERROR = "GET_NEW_AVAILABLE_SERVICES_REQUEST_ERROR"
// export const GET_NEW_AVAILABLE_SERVICES_REQUEST_RESET = "GET_NEW_AVAILABLE_SERVICES_REQUEST_RESET"

// export const CLEAR_NEW_AVAILABLE_FLAG_REQUEST = "CLEAR_NEW_AVAILABLE_FLAG_REQUEST";
// export const CLEAR_NEW_AVAILABLE_FLAG_REQUEST_SUCCESS = "CLEAR_NEW_AVAILABLE_FLAG_REQUEST_SUCCESS";
// export const CLEAR_NEW_AVAILABLE_FLAG_REQUEST_ERROR = "CLEAR_NEW_AVAILABLE_FLAG_REQUEST_ERROR"; 

// export const GET_INWARD_TARIFF_DATA_REQUEST = "GET_INWARD_TARIFF_DATA_REQUEST"
// export const GET_INWARD_TARIFF_DATA_REQUEST_SUCCESS = "GET_INWARD_TARIFF_DATA_REQUEST_SUCCESS"
// export const GET_INWARD_TARIFF_DATA_REQUEST_ERROR = "GET_INWARD_TARIFF_DATA_REQUEST_ERROR"

// export const UPDATE_INWARD_TARIFF_REQUEST = "UPDATE_INWARD_TARIFF_REQUEST"
// export const UPDATE_INWARD_TARIFF_REQUEST_SUCCESS = "UPDATE_INWARD_TARIFF_REQUEST_SUCCESS"
// export const UPDATE_INWARD_TARIFF_REQUEST_ERROR = "UPDATE_INWARD_TARIFF_REQUEST_ERROR"

// export const TARIFF_REVIEW_REQUEST = "TARIFF_REVIEW_REQUEST";
// export const TARIFF_REVIEW_REQUEST_SUCCESS = "TARIFF_REVIEW_REQUEST_SUCCESS";
// export const TARIFF_REVIEW_REQUEST_ERROR = "TARIFF_REVIEW_REQUEST_ERROR";

// export const GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST = "GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST"
// export const GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST_SUCCESS = "GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST_SUCCESS"
// export const GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST_ERROR = "GET_ROOM_CATEGORY_SELECTION_DETAIL_REQUEST_ERROR"

// export const CREATE_REFUND_INVOICE_REQUEST = "CREATE_REFUND_INVOICE_REQUEST"
// export const CREATE_REFUND_INVOICE_SUCCESS = "CREATE_REFUND_INVOICE_SUCCESS"
// export const CREATE_REFUND_INVOICE_ERROR = "CREATE_REFUND_INVOICE_ERROR"

// export const GET_HOSPITAL_DETAILS_BY_ID_REQUEST = "GET_HOSPITAL_DETAILS_BY_ID_REQUEST"
// export const GET_HOSPITAL_DETAILS_BY_ID_SUCCESS = "GET_HOSPITAL_DETAILS_BY_ID_SUCCESS"
// export const GET_HOSPITAL_DETAILS_BY_ID_ERROR = "GET_HOSPITAL_DETAILS_BY_ID_ERROR"

// export const HOSPITAL_DECIDER_SELECT_HOSPITAL = "HOSPITAL_DECIDER_SELECT_HOSPITAL"

// export const GET_EINVOICE_REQUEST = "GET_EINVOICE_REQUEST"
// export const GET_EINVOICE_SUCCESS = "GET_EINVOICE_SUCCESS"
// export const GET_EINVOICE_FAIL = "GET_EINVOICE_FAIL"


// export const GET_REFUND_REJECT_REASONS_REQUEST = "GET_REFUND_REJECT_REASONS_REQUEST"
// export const GET_REFUND_REJECT_REASONS_SUCCESS = "GET_REFUND_REJECT_REASONS_SUCCESS"
// export const GET_REFUND_REJECT_REASONS_ERROR = "GET_REFUND_REJECT_REASONS_ERROR"

// export const GET_COUNTRY_FLAGS_DIAL_CODES_REQUEST = "GET_COUNTRY_FLAGS_DIAL_CODES_REQUEST"
// export const GET_COUNTRY_FLAGS_DIAL_CODES_SUCCESS = "GET_COUNTRY_FLAGS_DIAL_CODES_SUCCESS"
// export const GET_COUNTRY_FLAGS_DIAL_CODES_ERROR = "GET_COUNTRY_FLAGS_DIAL_CODES_ERROR"

// export const GET_APPOINTMENT_SCHEDULING_SERVICES_REQUEST = "GET_APPOINTMENT_SCHEDULING_SERVICES_REQUEST"
// export const GET_APPOINTMENT_SCHEDULING_SERVICES_SUCCESS = "GET_APPOINTMENT_SCHEDULING_SERVICES_SUCCESS"
// export const GET_APPOINTMENT_SCHEDULING_SERVICES_ERROR = "GET_APPOINTMENT_SCHEDULING_SERVICES_ERROR"

// export const GET_FORM_BUILDER_TEMPLATE_SERVICES_REQUEST = "GET_FORM_BUILDER_TEMPLATE_SERVICES_REQUEST"
// export const GET_FORM_BUILDER_TEMPLATE_SERVICES_SUCCESS = "GET_FORM_BUILDER_TEMPLATE_SERVICES_SUCCESS"
// export const GET_FORM_BUILDER_TEMPLATE_SERVICES_ERROR = "GET_FORM_BUILDER_TEMPLATE_SERVICES_ERROR"

// export const SET_TEXT_FEAILD_VALUE  = "SET_TEXT_FEAILD_VALUE"
// export const SET_IMAGE_DATA_FEAILD_VALUE  = "SET_IMAGE_DATA_FEAILD_VALUE"
// export const SET_CHECK_BOXES_VALUE = "SET_CHECK_BOXES_VALUE"
// export const SET_SELECTED_FORM_TEMPLATE = "SET_SELECTED_FORM_TEMPLATE"
// export const CLEAR_SELECTED_FORM_TEMPLATE = "CLEAR_SELECTED_FORM_TEMPLATE"
// export const SET_IMAGE_EDITE_STATUS_VALUE  = "SET_IMAGE_EDITE_STATUS_VALUE"
// export const SET_DROP_DOWUN_VALUE = "SET_DROP_DOWUN_VALUE"

// export const CREATE_EXAMINATION_DATA_TO_EHR_REQUEST = "CREATE_EXAMINATION_DATA_TO_EHR_REQUEST"
// export const CREATE_EXAMINATION_DATA_TO_EHR_SUCCESS = "CREATE_EXAMINATION_DATA_TO_EHR_SUCCESS"
// export const CREATE_EXAMINATION_DATA_TO_EHR_ERROR = "CREATE_EXAMINATION_DATA_TO_EHR_ERROR"

// export const GET_EXAMINATION_DATA_TO_EHR_REQUEST = "GET_EXAMINATION_DATA_TO_EHR_REQUEST"
// export const GET_EXAMINATION_DATA_TO_EHR_SUCCESS = "GET_EXAMINATION_DATA_TO_EHR_SUCCESS"
// export const GET_EXAMINATION_DATA_TO_EHR_ERROR = "GET_EXAMINATION_DATA_TO_EHR_ERROR"

// export const PARTIALLY_PAID_INVOICE_DETAILS = "PARTIALLY_PAID_INVOICE_DETAILS"

// export const PRE_ASSESSMENT_DETAILS = "PRE_ASSESSMENT_DETAILS";
// export const PRE_ASSESSMENT_SUMMARY_DETAILS = "PRE_ASSESSMENT_SUMMARY_DETAILS";
// export const RESET_PRE_ASSESSMENT_DETAILS = "RESET_PRE_ASSESSMENT_DETAILS";

// export const CHANGE_USER_FAVORITES = "CHANGE_USER_FAVORITES";
// export const RESET_USER_FAVORITES = "RESET_USER_FAVORITES";

// export const SET_SELECTED_STORE = "SET_SELECTED_STORE";
// export const GET_ACKNOWLEDGEMENT_POPUP_REQUEST = "GET_ACKNOWLEDGEMENT_POPUP_REQUEST"
// export const GET_ACKNOWLEDGEMENT_POPUP_SUCCESS = "GET_ACKNOWLEDGEMENT_POPUP_SUCCESS"
// export const GET_ACKNOWLEDGEMENT_POPUP_FAIL = "GET_ACKNOWLEDGEMENT_POPUP_FAIL"
// export const GET_ACKNOWLEDGEMENT_POPUP_CONTINUE = "GET_ACKNOWLEDGEMENT_POPUP_CONTINUE"
// export const GET_ACKNOWLEDGEMENT_POPUP_OPEN = "GET_ACKNOWLEDGEMENT_POPUP_OPEN"


// export const UPDATE_CLINICAL_STAFF_CLINIC_STATION_PAYLOAD = "UPDATE_CLINICAL_STAFF_CLINIC_STATION_PAYLOAD";
// export const UPDATE_CLINICAL_STAFF_STRUCTURE_ACTIVE_ELEMENT = 'UPDATE_CLINICAL_STAFF_STRUCTURE_ACTIVE_ELEMENT';
// export const RESET_CLINICAL_STAFF_CLINIC_STATION_PAYLOAD = "RESET_CLINICAL_STAFF_CLINIC_STATION_PAYLOAD";

// export const UPDATE_NON_CLINICAL_STAFF_DEPARTMENT_STRUCTURE = "UPDATE_NON_CLINICAL_STAFF_DEPARTMENT_STRUCTURE";
// export const UPDATE_NON_CLINICAL_STAFF_STRUCTURE_ACTIVE_ELEMENT = "UPDATE_NON_CLINICAL_STAFF_STRUCTURE_ACTIVE_ELEMENT";
// export const RESET_NON_CLINICAL_STAFF_DEPARTMENT_STRUCTURE = "RESET_NON_CLINICAL_STAFF_DEPARTMENT_STRUCTURE";

// export const GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_REQUEST = "GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_REQUEST";
// export const GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_SUCCESS = "GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_SUCCESS";
// export const GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_ERROR = "GET_HOSPITAL_CONFIGURATION_DETAILS_BY_ID_ERROR";


// export const GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_REQUEST = "GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_REQUEST";
// export const GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_SUCCESS = "GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_SUCCESS";
// export const GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_FAIL = "GET_INSURANCE_PENDINGAPPROVAL_SUMMARY_FAIL";

// export const SAVE_PATIENT_ID = "SAVE_PATIENT_ID";

// export const SAVE_CLICKED_SURGERY_APPOINTMENT = "SAVE_CLICKED_SURGERY_APPOINTMENT";
// export const SAVE_CLICKED_ITEM = "SAVE_CLICKED_ITEM"

// export const ACCEPT_PHARMACY_ITEM_REQUEST = "ACCEPT_PHARMACY_ITEM_REQUEST"
// export const ACCEPT_PHARMACY_ITEM_SUCCESS = "ACCEPT_PHARMACY_ITEM_SUCCESS"
// export const ACCEPT_PHARMACY_ITEM_ERROR = "ACCEPT_PHARMACY_ITEM_ERROR"


// Exotic Globbal Holidays


export const SAVE_CLICKED_GUIDEDATA = "SAVE_CLICKED_GUIDEDATA"; 
export const SAVE_CLICKED_VEHICLE_SUPPLIIER = "SAVE_CLICKED_VEHICLE_SUPPLIIER";
export const SAVE_CLICKED_LOCATIONDATA = "SAVE_CLICKED_LOCATIONDATA";
export const SAVE_CLICKED_ACTIVITY = "SAVE_CLICKED_ACTIVITY";
export const CLEAR_CLICKED_ACTIVITY = "CLEAR_CLICKED_ACTIVITY";
export const SAVE_CLICKED_EVENT = "SAVE_CLICKED_EVENT";
export const CLEAR_CLICKED_EVENT = "CLEAR_CLICKED_EVENT";